### ISSUE TITLE
Give the control-plane API its own top-level folder in the repo

### ISSUE THREAD

**Issue by aldemirenes** [snowplow/snowplow-mini#100]
Folder of the control-plane API will be in the main directory of the repo

**Comment by alexanderdean** [comment]
This doesn't need to be its own commit or ticket - think of a commit as a delta between the last version, 0.2.0, and this version, 0.3.0. This commit should be merged into the commit and ticket for adding the Control Plane API.

**Comment by aldemirenes** [comment]
Commits are merged @alexanderdean  , will be pushed a little later.
