### ISSUE TITLE
Add test for control-plane API to integration-test.sh

### ISSUE THREAD

**Issue by aldemirenes** [snowplow/snowplow-mini#101]

**Comment by alexanderdean** [comment]
This doesn't need to be its own commit or ticket - think of a commit as a delta between the last version, 0.2.0, and this version, 0.3.0. This commit should be merged into the commit and ticket for adding the Control Plane API.

**Comment by aldemirenes** [comment]
Commits are merged Alex, will be pushed a litlte later.
