### ISSUE TITLE
Use ansible playbooks in .travis.yml

### ISSUE THREAD

**Issue by aldemirenes** [snowplow/snowplow-mini#102]
In the Snowplow-Mini v0.2.2, travis build is made with shell scripts. But in the Snowplow-Mini v0.3.0, provisioning will be made with ansible playbooks therefore it will be good if ansible playbooks are used with travis too.

**Comment by alexanderdean** [comment]
I understand the description (I think), but the ticket name is vague. I can't read the ticket name and understand what is taking place.

**Comment by aldemirenes** [comment]
Merged with [this ticket](https://github.com/snowplow/snowplow-mini/issues/52), closing
