### ISSUE TITLE
Add domain name to Caddyfile for TLS via user_data.sh 

### ISSUE THREAD

**Issue by aldemirenes** [snowplow/snowplow-mini#105]
Lets Encrypt does not make certificate for ip numbers therefore domain name is necessary for TLS connection. User will be able to submit domain name with user_data.sh and will be able to connect to snowplow-mini with TLS.

**Comment by alexanderdean** [comment]
Thanks @aldemirenes. Can you itemise what currently has to go in the user_data?

**Comment by aldemirenes** [comment]
*uuid for iglu server
* domain name
* user email
* tls on/off selection

I will add this list to the wiki for v0.3.0

**Comment by alexanderdean** [comment]
Thanks!

**Comment by alexanderdean** [comment]
Changed title, please reword commit
