### ISSUE TITLE
Placeholder for new Control Plane API tickets

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-mini#109]

**Comment by alexanderdean** [comment]
@aldemirenes please split this into individual tickets of the title

"Add Control Plane API call to ..."

**Comment by alexanderdean** [comment]
You can write a list of the new tickets as a comment in this ticket, then close this ticket and de-schedule it from the milestone.

**Comment by aldemirenes** [comment]
- Add Control Plane API call to write domain name to Caddyfile for automatic TLS [#118](https://github.com/snowplow/snowplow-mini/issues/118)
- Add Control Plane API call to change username and password for basic http authentication [#117](https://github.com/snowplow/snowplow-mini/issues/117)
- Add Control Plane API call to add apikey for Iglu authentication [#116](https://github.com/snowplow/snowplow-mini/issues/116)
- Add Control Plane API call to put your own custom enrichments in Snowplow Mini [#66](https://github.com/snowplow/snowplow-mini/issues/66)
- Add Control Plane API call to add external Iglu schema registry to snowplow-mini [#62](https://github.com/snowplow/snowplow-mini/issues/62)
