### ISSUE TITLE
Getting unauthorized error while trying to upload schemas to Iglu with Iglu Server Swagger UI

### ISSUE THREAD

**Issue by aldemirenes** [snowplow/snowplow-mini#111]
While there is no problem in the keygen sections, getting unauthorized error while trying to upload schemas to Iglu. Also, there is no problem while uploading with igluctl when this problem occurs and this means that using wrong apiKey case is eliminated.

**Comment by jbeemster** [comment]
The master api_key cannot be used to upload schemas.  It can only be used to generate api_keys that can then upload schemas.  Under the hood in igluctl this is what it is doing.
