### ISSUE TITLE
Deploy Caddy so that each app is on an authenticated sub-path

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-mini#12]
e.g. /elasticsearch, /kibana, /collector etc.

Nice to do if we have time...

**Comment by yalisassoon** [comment]
This would allow us to reduce the number of ports that need to be opened in the security group.

**Comment by alexanderdean** [comment]
@jbeemster to update this ticket with a full set of mappings

**Comment by alexanderdean** [comment]
Renamed ticket, please reword commit. Also note that I have changed the name so that you can add the HTTP auth into this commit...
