### ISSUE TITLE
Iglu-compatible Webhook not working

### ISSUE THREAD

**Issue by narsariamanu** [snowplow/snowplow-mini#121]
I have declared a JSON Schema for onesignal.com and according to iglu-CTL, it is a valid schema. I have uploaded the schema to Iglu Server. On Pinging the webhook with data, I am getting the following error:

> {"level":"error","message":"Querystring is empty: no Iglu-compatible event to process"}

I am trying to do a POST request as stated [here](https://github.com/snowplow/snowplow/wiki/Iglu-webhook-setup)

**Comment by alexanderdean** [comment]
Hi @narsariamanu - sorry to hear you are having problems. This isn't a Snowplow Mini-specific issue, so I'm closing it, but feel free to post to our forums:

http://discourse.snowplowanalytics.com/

**Comment by narsariamanu** [comment]
@alexanderdean But this issue is coming along with the Scala Common Enrich that comes with Snowplow-mini.
