### ISSUE TITLE
Links broken if trailing slash is not present

### ISSUE THREAD

**Issue by ungn** [snowplow/snowplow-mini#123]
This applies to the following endpoints tested:

- `http://<ip>/spmini`-> see [screenshot](https://trello-attachments.s3.amazonaws.com/57823b3443ccdf83661d01b2/57b433eb006060224ff2e038/886ad47d0472937a77b1ed4ee00c422b/Screen_Shot_2017-08-17_at_12.13.56.png)
- `http://<ip>/iglu-server` -> see [screenshot](https://trello-attachments.s3.amazonaws.com/57823b3443ccdf83661d01b2/57b433eb006060224ff2e038/748a520ae2671b60df9d93fc5c26b12a/Screen_Shot_2017-08-17_at_11.42.33.png)
- `http://<ip>/kibana`-> see [screenshot](https://trello-attachments.s3.amazonaws.com/57823b3443ccdf83661d01b2/57b433eb006060224ff2e038/5fc35794d6634d467481a3d58bf62527/Screen_Shot_2017-08-17_at_12.14.27.png)
- `http://<ip>/elasticsearch/_plugin/head` -> `404 Not Found` (existing behaviour redirects to slash endpoint)

This one still works without a trailing slash:
- `http://<ip>/elasticsearch`

Endpoints work as expected with the trailing slash in place.

**Comment by aldemirenes** [comment]
All internal requests from page are sent like http://<ip>/<webpage-internal-api> without traling slash. Since we are using proxy server, requests must be sent like from http://<ip>/<tool-name>/<webpage-internal-api> in order to redirect them correct internal port. Therefore there must be trailing slash for endpoint of the tools which use internal resources such as css or other internal api request. This issue is a little bit subtle, if I could not express the issue clearly, feel free to ask questions.

**Comment by ungn** [comment]
Is there no way around this issue? This is potentially confusing for clients who are already familiar with Snowplow Mini and attempt to use the new version in the same way.

Even redirecting to an error page which informs of the need for the trailing slash would be better than the current behaviour.

**Comment by jbeemster** [comment]
@aldemirenes could redirects be setup to automatically move a user to the correct URL?

https://caddyserver.com/docs/redir

**Comment by aldemirenes** [comment]
@jbeemster Will look into it.

**Comment by aldemirenes** [comment]
Problem is solved with "redir", will be pushed with other changes for the PR

**Comment by jbeemster** [comment]
I believe this ticket can be closed as it was done as part of the last release?

**Comment by aldemirenes** [comment]
Yes, it is fixed with commit https://github.com/snowplow/snowplow-mini/commit/4b2653b729c4bb44c92b196db9389bb62c32874a.
