### ISSUE TITLE
No basic auth requested for /iglu-server endpoint

### ISSUE THREAD

**Issue by ungn** [snowplow/snowplow-mini#124]
After spinning up a new instance and accessing `http://<ip>/iglu-server/` directly, Swagger interface appears without requesting for any authentication.

See [screenshot](https://trello-attachments.s3.amazonaws.com/57823b3443ccdf83661d01b2/57b433eb006060224ff2e038/a9de2e467d7320e5f74ecb67e81101c8/Screen_Shot_2017-08-17_at_13.46.44.png).

**Comment by aldemirenes** [comment]
Since private schemas on the iglu server can be accessed with api key only and iglu server can have public schemas, iglu-server endpoint did not included to the endpoints which accessed with http auth. This is expected behaviour.

**Comment by ungn** [comment]
Can confirm behaviour - private schemas only accessible with valid API key.
Closing.
