### ISSUE TITLE
Use Caddy instead of Nginx for serving the Snowplow Mini dashboard

### ISSUE THREAD

**Issue by aldemirenes** [snowplow/snowplow-mini#130]
Since this is a static website and load of the dashboard is not too big, I think caddy server can handle it pretty well. What do you think ? @jbeemster @alexanderdean

**Comment by alexanderdean** [comment]
Can you remind me what else Nginx is used for?

**Comment by aldemirenes** [comment]
It is only used for serving dashboard. After making transition to caddy server for serving dashboard, we can remove it from Snowplow Mini.

**Comment by alexanderdean** [comment]
Oh nice!

**Comment by alexanderdean** [comment]
Improved ticket name, please update commit and changelog
