### ISSUE TITLE
Missing section on Custom Enrichment in Quickstart Guide

### ISSUE THREAD

**Issue by dilyand** [snowplow/snowplow-mini#131]
https://github.com/snowplow/snowplow-mini/wiki/Quickstart-guide has a ToC item for Custom Enrichments but there is no such section in the body of the article.

**Comment by aldemirenes** [comment]
Added with this [revision](https://github.com/snowplow/snowplow-mini/wiki/Quickstart-guide/fbb63b4d89b18672774ee01b378417442cb65fbc).
