### ISSUE TITLE
Add libffi-dev, libssl-dev, python-dev and markupsafe as dependencies

### ISSUE THREAD

**Issue by aldemirenes** [snowplow/snowplow-mini#133]
Vagrant setup is giving error while installing ansible currently. I think this error arose due to some internal changes in the pip ansible package. You should add following lines to before [ansible install](https://github.com/snowplow/snowplow-mini/blob/master/vagrant/up.bash#L14) command in vagrant/up.bash file :
```
sudo apt-get install libffi-dev
sudo apt-get install libssl-dev
sudo apt-get install python-dev
sudo pip install markupsafe
```
This will be fixed in the next release.

**Comment by alexanderdean** [comment]
Improved ticket name, please update commit and changelog
