### ISSUE TITLE
Instructions on endpoint incorrect

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/snowplow-mini#134]
Step 5.1 instructs users to input `http://< the public ip>` as the endpoint when sending events. This should just be `< the public ip>`

**Comment by colmsnowplow** [comment]
https://github.com/snowplow/snowplow-mini/wiki/Quickstart-guide#51-try-sending-events-from-other-places

**Comment by BenFradet** [comment]
Thanks, fixed 👍
