### ISSUE TITLE
Iglu adapter POST fails if schema in querystring

### ISSUE THREAD

**Issue by ihortom** [snowplow/snowplow-mini#138]
The `POST` requests could be sent to Iglu adapter in 2 ways:

> - As a full SelfDescribing JSON in the body
> - With a `?schema=<iglu schema uri>` in the querystring and a data JSON in the body
>
> Source: [wiki](https://github.com/snowplow/snowplow/wiki/Iglu-webhook-setup#215-example-post-request)

The 2nd option fails with "Iglu event failed: detected SelfDescribingJson but schema key is missing". However, it does work in Scala collector for RT pipeline.

**Comment by alexanderdean** [comment]
Bringing forwards as it's a bit of a bug.

**Comment by BenFradet** [comment]
I think this is just due to a version issue, the current snowplow mini uses ssc 0.9 which doesn't pass the query string for post requests, the new versions do pass it.

Anyway I'll try it out with the new ssc.

**Comment by alexanderdean** [comment]
Thanks @BenFradet !

**Comment by BenFradet** [comment]
yup, works with the upgraded collector, closing
