### ISSUE TITLE
Create script for setting up Iglu repo and bucket for jsonpath file

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-mini#14]
The script should take two arguments:

1. Bucket name for iglu static server repo
2. Bucket name for jsonpath file

Bonus if script can generate a customized version of https://github.com/snowplow/snowplow-mini/blob/master/resources/iglu/README.md

**Comment by yalisassoon** [comment]
I don't remember what this issue was about? It makes no sense to me now...

**Comment by jbeemster** [comment]
I think this was to allow for loading into Redshift probably with the need for JsonPaths?

**Comment by alexanderdean** [comment]
Closing, follow https://github.com/snowplow/snowplow-mini/milestone/9 for Redshift loading planning.
