### ISSUE TITLE
Add ami-factory credentials to .travis.yml

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-mini#143]
- AWS_DEPLOY_ACCESS_KEY
- AWS_DEPLOY_SECRET_KEY

**Comment by BenFradet** [comment]
Note that this is the creds for the Hosted assets account

**Comment by oguzhanunlu** [comment]
Hey @alexanderdean , can you please encrypt those variables and open a PR? I'll handle the rest.

**Comment by jbeemster** [comment]
Hey @oguzhanunlu I handle the creds for that account :) - Is there a particular branch you want me to commit into?

**Comment by oguzhanunlu** [comment]
Thanks @jbeemster , commit on top of my release branch, `v0.6.0`. Please ping me once you do.
