### ISSUE TITLE
Add simple query API for integration testing

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-mini#166]
If you want to add Snowplow Mini into an integration test (e.g. for a webapp), then Elasticsearch is massive overkill.

All you really want is a simple endpoint on the Mini:

```
snowplow-mini.local/events/${eventId}
```

which returns either the successfully enriched event (probably JSON transformed), or the corresponding bad record.

This would be super-useful for automated testing, where you just want to track an event and inspect the result without any human involvement.

**Comment by BenFradet** [comment]
mmmh a rest-enrich project could indeed be excellent.

**Comment by alexanderdean** [comment]
> mmmh a rest-enrich project could indeed be excellent.

This would be nice as actually it's quite problematic having to either a) bring up a dedicated EC2 instance or b) all of a Snowplow Mini's constituent micro-services just to achieve the above.

Snowplow Micro? 🔬

**Comment by poberherr** [comment]
Agreed to @alexanderdean , the main point just would be that a CI process could spawn a test per branch. 

Eventually there are multiple PR's to the schema registry and I think it makes scene to have each new schema tested individually.

One thing I took a look at (as a brainteaser) :
https://chrome.google.com/webstore/detail/snowplow-inspector/maplkdomeamdlngconidoefjpogkmljm
This plugin somehow validates, if the schema is valid or not, most likely with a completely different approach ( I am curious how they do it ).

**Comment by miike** [comment]
This would be nice to add to the chrome extension too

cc @jethron

**Comment by jethron** [comment]
Yeah, an API like this would be cool; especially if the extension can do a "force to mini" feature so you can get end-to-end validation of all your web event tracking.

@poberherr Only just saw this, sorry; the extension just takes a list of Iglu repositories and checks each schema against them all, and then does a JSON Schema validation against the `data` Object once it finds a match.

**Comment by oguzhanunlu** [comment]
Closing as we have Snowplow Micro now
