### ISSUE TITLE
Install NTP

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/snowplow-mini#167]
NTP isn't installed by default on Ubuntu 14.04, base image of sp mini. It should be installed to avoid possible clock drifts.

**Comment by jbeemster** [comment]
Not a bad idea to make a note of the required outbound port for this to work in the documentation - UDP 123 by default.

**Comment by oguzhanunlu** [comment]
Thanks @jbeemster , not a bad idea for sure. Took my note to update docs once the release is out.
