### ISSUE TITLE
Disable _ttl for ES indexes

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/snowplow-mini#168]
Elasticsearch `1.7` isn't maintained anymore and there are bug discussions around `_timestamp` and `_ttl`.

Upgrading ES to a modern version will prevent most of the headaches coming from not maintained old version. Until then, let's disable `_ttl`.

**Comment by jbeemster** [comment]
Hey @oguzhanunlu whats the plan to manage the document age in lieu of having a `_ttl`?  We probably still want to enforce expiration of documents to prevent the mini from filling up.

**Comment by oguzhanunlu** [comment]
@jbeemster right, [curator](https://www.elastic.co/blog/curator-tending-your-time-series-indices) might be an option.

**Comment by oguzhanunlu** [comment]
This is handled as part of dockerization sp mini, see #23 .
