### ISSUE TITLE
vagrant setup is broken

### ISSUE THREAD

**Issue by davidsiefert** [snowplow/snowplow-mini#171]
Trying to do `vagrant up` and it fails on an npm install command for the ui (permissions issue, will post exact error a little later).  However, I make the following change and this gets around the issue:

```diff
diff --git a/provisioning/roles/sp_mini_5_build_ui/tasks/main.yml b/provisioning/roles/sp_mini_5_build_ui/tasks/main.yml
index 1dd0bd2..3f079aa 100644
--- a/provisioning/roles/sp_mini_5_build_ui/tasks/main.yml
+++ b/provisioning/roles/sp_mini_5_build_ui/tasks/main.yml
@@ -2,10 +2,8 @@
 - include_vars: ../../common_vars.yml

 - name: Install npm packages based on package.json.
-  become: yes
   npm:
     path: "{{playbook_dir}}/resources/ui"

 - name: Create dist files
-  become: yes
   shell: "cd {{playbook_dir}}/resources/ui; tsc -p js --outDir dist/ && browserify dist/SnowplowMiniApp.js -o dist/bundle.js && uglifyjs dist/bundle.js > dist/snowplow-mini.js"
```

**Comment by oguzhanunlu** [comment]
Hi @davidsiefert , thanks for the notice. I haven't encountered this so far but I'll investigate and get back.

**Comment by davidsiefert** [comment]
Odd, I stashed my changes and reran `vagrant up` 2x already... magically working.

**Comment by jbeemster** [comment]
In my experience this can sometimes happen with npm and the Vagrantfile NFS option:

https://github.com/snowplow/snowplow-mini/blob/master/Vagrantfile#L7-L9

The option greatly speeds up the filesystem but can cause issues when writing files to the shared directory sometimes.

**Comment by BenFradet** [comment]
thanks @jbeemster , closing
