### ISSUE TITLE
Bump Stream Enrich to 0.18.0

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-mini#174]
there is a huge impedance mismatch between snowplow/snowplow release frequency and mini's which defeats the purpose of a qa pipeline (e.g. with the pii enrichment)

**Comment by alexanderdean** [comment]
Should this go into the current release?

**Comment by BenFradet** [comment]
yup, sorry @oguzhanunlu :disappointed:

**Comment by oguzhanunlu** [comment]
I like it dynamic @BenFradet ! Should we bump to `0.17.0` ? It is latest stable [available](https://bintray.com/snowplow/registry/snowplow%3Astream-enrich-nsq/0.17.0) from bintray right now.

**Comment by BenFradet** [comment]
it'll basically be a race between mini 0.6.0 and R107, either you win and it'll be 0.17.0 or Rostyslav wins and it'll be 0.18.0 :D

**Comment by BenFradet** [comment]
Note that this version of enrich needs a new nsq topic (for pii events)

**Comment by jbeemster** [comment]
So I think for the sake of keeping the mini working this should be disabled - no one will be able to consume the PII Stream - the data in the PII Stream will also not be surfaced anywhere.  Badly configuring the PII enrichment or stream enrich will also break things as the settings need to map together very accurately.

I would vote for not allowing a PII stream at all at this point.

**Comment by BenFradet** [comment]
>the data in the PII Stream will also not be surfaced anywhere

? it'll be in NSQ and people want to test their pii enrichment in mini

**Comment by BenFradet** [comment]
discussed with Josh and subsequently logged snowplow/snowplow#3828 as it is very much impractical, we can't realistically enable the pii enrichment in its newer version atm...

**Comment by BenFradet** [comment]
the validation is only performed for Kinesis (which is a bug snowplow/snowplow#3829) so we can enable the new pii enrichment as it is.

a new nsq topic will need to be created.

**Comment by BenFradet** [comment]
The decision was to provide a default pii enrichment which does nothing.

**Comment by alexanderdean** [comment]
We will also need to update the documentation to explain how to update that enrichment if you want to change the configuration (e.g. the NSQ topic name must **not** be changed).

**Comment by BenFradet** [comment]
Bumped to 0.18.0 since we'll be releasing it today
