### ISSUE TITLE
Add check that tables exist and create them if not

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-mini#18]
From the structure of the shredded data it is possible to infer the required table name 

e.g.:  
- `com.snowplowanalytics.snowplow/ua_parser_context/jsonschema/1-0-0/` -> com_snowplowanalytics_snowplow_ua_parser_context_1 (https://github.com/snowplow/snowplow/blob/master/4-storage/redshift-storage/sql/com.snowplowanalytics.snowplow/ua_parser_context_1.sql)
- `org.openweathermap/weather/jsonschema/1-0-0/` -> org_openweathermap_weather_1 (https://github.com/snowplow/snowplow/blob/master/4-storage/redshift-storage/sql/org.openweathermap/weather_1.sql)

**Comment by alexanderdean** [comment]
Won't fix, this will be done eventually by RDB Loader.
