### ISSUE TITLE
Explore exporting logs through CloudWatch

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-mini#188]
Integration could look like this (https://docs.docker.com/config/containers/logging/awslogs/):

```sh
--log-driver awslogs \
--log-opt awslogs-group=mini-xx/container \
--log-opt awslogs-stream=`ec2metadata --instance-id` \
```

Thanks @jbeemster 

There is also GCP Logging integration available: https://docs.docker.com/config/containers/logging/gcplogs/#gcplogs-options, for a separate ticket.

**Comment by oguzhanunlu** [comment]
Closing the ticket as it is introduced in 0.12.0 for both AWS & GCP.
