### ISSUE TITLE
Make it possible to refresh Elasticsearch index mapping

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-mini#192]
Many Snowplow users use Snowplow Mini to test schemas in development, before pushing them to production. As part of this process they will mutate their schemas. Certain mutations necessitate remappings in Elasticsearch, creating two problems:

1. When this happens it isn't obvious to users: all that it looks like is that bad events are landing bug good aren't, which is baffling.
2. There's no obvious way for clients to do the remapping. (Ideally this would be done automatically.)

See https://snowplow.zendesk.com/agent/tickets/13866 for an example

**Comment by oguzhanunlu** [comment]
a new endpoint of Control Plane API could reset existing index mapping to default mapping to undo the recent changes
