### ISSUE TITLE
Fix enrichment upload mechanism

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-mini#194]
For some reason the upload of enrichment does not replace the whole file but rather just changes the lines in the file - in the case that the old enrichment JSON is longer than the new one you will end up with corrupted input which will break Stream Enrich.

**Comment by jbeemster** [comment]
This function needs to delete the existing file first or at least empty it out before attempting upload:

https://github.com/snowplow/snowplow-mini/blob/master/provisioning/resources/control-plane/main.go#L98-L103

**Comment by oguzhanunlu** [comment]
Just like here https://github.com/snowplow/snowplow-mini/blob/master/provisioning/resources/control-plane/main.go#L148-L155 . All config updating functions must follow this approach.
