### ISSUE TITLE
Upgrading snowplow mini GCP instance from 0.7 to 0.8

### ISSUE THREAD

**Issue by alperakgun** [snowplow/snowplow-mini#225]
Is it possible to upgrade  a snowplow mini GCP instance from 0.7 to 0.8 without reinstall?

**Comment by paulboocock** [comment]
Hi @alperakgun 
Questions are usually best placed over on our Discourse where we have more community activity: https://discourse.snowplowanalytics.com/

In general though, Snowplow Minis are not designed to be upgradable. They are designed to be thrown away and spun back up for testing and development of Snowplow tracking. Perhaps open a thread over on Discourse to see how other community members handle migrating between Snowplow Mini versions.
