### ISSUE TITLE
Unable to launch an AWS Mini in 172.18.0.0/16

### ISSUE THREAD

**Issue by jparavisini** [snowplow/snowplow-mini#226]
Strange issue – Launching a snowplow mini (tested with 0.8.0 and 0.6.4) from the community AMI section in ec2 results in an instance with no system logs and no ability to connect. From preliminary digging, the suspicion is that this is due to a conflict between docker's default bridge network range, which grabs the first available subnet after 172.17.0.0. 

Assuming this could be solved by making the network range configurable rather than relying on docker's default behavior.

**Comment by oguzhanunlu** [comment]
Hi @jparavisini , could you share all the steps you take so that I can reproduce the case and investigate further? Thanks in advance.

**Comment by jparavisini** [comment]
Sure thing @oguzhanunlu,

- Create a new VPC with 172.18.0.0/16 as the CIDR range
- Create a subnet within that VPC. Any valid subnet should work, but I have personally tested so far with 172.18.1.0/24,172.18.2.0/24,172.18.20.0/24 and 172.18.21.0/24
- Launch a new mini using the community AMI within the subnet created above.
