### ISSUE TITLE
Replace Gitter button with Discourse button

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-mini#261]
The README has a link to Gitter chat - are we actively maintaining that as a discussion forum?

/cc @goodits

**Comment by paulboocock** [comment]
With the monorepo split, we made the call to remove Gitter chat from `snowplow/snowplow` as we no longer actively watch the rooms (https://github.com/snowplow/snowplow/issues/4418) and would prefer to send people to [discourse](https://discourse.snowplowanalytics.com/), I believe the same would apply here too.

**Comment by alexanderdean** [comment]
Makes sense. How about we come up with a nice button to drive to Discourse, and replace the Gitter button with that?

**Comment by paulboocock** [comment]
[![Discourse posts](https://img.shields.io/discourse/posts?server=https%3A%2F%2Fdiscourse.snowplowanalytics.com%2F)](https://discourse.snowplowanalytics.com/)

`[![Discourse posts](https://img.shields.io/discourse/posts?server=https%3A%2F%2Fdiscourse.snowplowanalytics.com%2F)](https://discourse.snowplowanalytics.com/)`
