### ISSUE TITLE
Increase Elasticsearch's limit on total number of fields

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/snowplow-mini#262]
[The default limit](https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-settings-limit.html#mapping-settings-limit) of 1000 is so low our users started to hit this limit

**Comment by chuwy** [comment]
Can we make it configurable?

**Comment by oguzhanunlu** [comment]
We can but that would delay the release, so we can open an issue to handle it in another release

**Comment by oguzhanunlu** [comment]
Closing as Elasticsearch API allows to configure this out of the box
