### ISSUE TITLE
Build fails because of bintray image 403

### ISSUE THREAD

**Issue by N0ps32** [snowplow/snowplow-mini#275]
Currently it's impossible to build the VM because bintray returns forbidden when pulling snowplow-docker-registry.bintray.io/snowplow/elasticsearch-loader:1.0.0:

default: fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "cd /home/ubuntu/snowplow && docker-compose up -d && sleep 20", "delta": "0:01:01.392193", "end": "2021-04-12 16:05:20.248516", "msg": "non-zero return code", "rc": 1, "start": "2021-04-12 16:04:18.856323", "stderr": "Creating network \"snowplow_default\" with the default driver\nPulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.9)...\nPulling kibana (docker.elastic.co/kibana/kibana-oss:6.8.9)...\nPulling elasticsearch-loader-good (snowplow-docker-registry.bintray.io/snowplow/elasticsearch-loader:1.0.0)...\nerror pulling image configuration: error parsing HTTP 403 response body: invalid character 'F' looking for beginning of value: \"Forbidden!\"", "stderr_lines": ["Creating network \"snowplow_default\" with the default driver", "Pulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.9)...", "Pulling kibana (docker.elastic.co/kibana/kibana-oss:6.8.9)...", "Pulling elasticsearch-loader-good (snowplow-docker-registry.bintray.io/snowplow/elasticsearch-loader:1.0.0)...", "error pulling image configuration: error parsing HTTP 403 response body: invalid character 'F' looking for beginning of value: \"Forbidden!\""], "stdout": "6.8.9: Pulling from elasticsearch/elasticsearch-oss\nDigest: sha256:2e55f2aa14bcf945bb04105d8faf8033e3a38242681060b6c1799c9cc920cbed\nStatus: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.9\n6.8.9: Pulling from kibana/kibana-oss\nDigest: sha256:cce63f95f522f0a7671213860d72e1f86aef21529555ff8b1ffab6a8b6e8e7cc\nStatus: Downloaded newer image for docker.elastic.co/kibana/kibana-oss:6.8.9\n1.0.0: Pulling from snowplow/elasticsearch-loader", "stdout_lines": ["6.8.9: Pulling from elasticsearch/elasticsearch-oss", "Digest: sha256:2e55f2aa14bcf945bb04105d8faf8033e3a38242681060b6c1799c9cc920cbed", "Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.9", "6.8.9: Pulling from kibana/kibana-oss", "Digest: sha256:cce63f95f522f0a7671213860d72e1f86aef21529555ff8b1ffab6a8b6e8e7cc", "Status: Downloaded newer image for docker.elastic.co/kibana/kibana-oss:6.8.9", "1.0.0: Pulling from snowplow/elasticsearch-loader"]}

You can easily test this outside the vagrant build process by running:
```
docker pull snowplow-docker-registry.bintray.io/snowplow/elasticsearch-loader:1.0.0
```

I've tested this from multiple IPs so I assume this is not an issue with me being rate-limited

**Comment by paulboocock** [comment]
Today is a scheduled "brown out" day for Bintray as it progresses to deprecation in May. 

We are in the progress of moving our docker to DockerHub and will publish a new mini build once that work is complete.

**Comment by paulboocock** [comment]
I've created https://github.com/snowplow/snowplow-mini/issues/276 so this is resolved in the next release.
