### ISSUE TITLE
 Connection refused error when trying to add apikey for local IGLU server on Snowplow mini

### ISSUE THREAD

**Issue by piotrstarzynski** [snowplow/snowplow-mini#295]
I created GCP instance (Snowplow Mini 0.12.5 because I couldn't see link to 0.12.6) based on the tutorial. The control panel working fine. It's available, but a few options inside it are not working.

I tried hard reset of instance via GCP with no change.

When trying to restart services through Control Plane: Error while restarting services, you need to hard reset your server
Trying to add Iglu Apikey: Error:dial tcp 127.0.0.1:5433: connect: connection refused 
Elasticsearch&iglu-server&Kibana: 502 Bad Gateway

I have found nothing inside logs so far.

**Comment by piotrstarzynski** [comment]
It looks like 0.12.5 is corrupted somehow. I tried with 0.11.0 and it's better. The only problem now is ElasticSearch.

When I try to enter Kibana: Unable to connect to Elasticsearch at http://elasticsearch:9200

What can I do?

**Comment by dilyand** [comment]
Hi @piotrstarzynski , indeed Mini 0.12.5 is broken for GCP. We've addressed this in https://github.com/snowplow/snowplow-mini/issues/283. Could you please try 0.12.6? The setup should be the same as for 0.12.5.

**Comment by piotrstarzynski** [comment]
How about the correct storage.googleapis.com link to 0.12.6?

**Comment by dilyand** [comment]
Ah, yes, of course. Sorry. Here they are:

```
"0.12.6-large"   = "https://storage.googleapis.com/snowplow-mini/snowplow-mini-0-12-6-large-1620758445.tar.gz"
"0.12.6-xlarge"  = "https://storage.googleapis.com/snowplow-mini/snowplow-mini-0-12-6-xlarge-1620748932.tar.gz"
"0.12.6-xxlarge" = "https://storage.googleapis.com/snowplow-mini/snowplow-mini-0-12-6-xxlarge-1620748943.tar.gz"
```

**Comment by piotrstarzynski** [comment]
Works now! Thank You
