### ISSUE TITLE
Upgrade base AMI from Ubuntu 18.04 to Ubuntu 20.04

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-mini#372]
We are fast approaching End of Standard Support for the current version (April 2023).  Would be good to get a build out that bumps to 20.04 which has support until April 2025.

cc/ @stanch

**Comment by ScullWM** [comment]
Any update on this topic ?

**Comment by stanch** [comment]
Hi @ScullWM, it’s on our list, should probably happen in the next few weeks.

**Comment by stanch** [comment]
Closing in favor of #381 which mentions an even newer Ubuntu version
