### ISSUE TITLE
Add management and overview UI for Snowplow Mini

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-mini#39]
As there are a lot of services running under the hood it would be good to be able to show the flow of information and the state of the services running that do not have an easy to digest UI.  

![ui-example](https://cloud.githubusercontent.com/assets/7984544/14205413/3c9df0d6-f80b-11e5-877e-cabe421ed958.jpg)

**Comment by jbeemster** [comment]
This could be expanded also to have:

* A section to send Javascript events from such as the example pages we have currently.
* When we have support for local postgres shredding a place to view the stored events.

In the end a fully comprehensive management suite for Snowplow Mini which could be eventually decomposed to manage the equally distributed set of appliances we deploy.

**Comment by alexanderdean** [comment]
I like it but it feels a bit "big bang" to me. Couldn't the v1 just be a "static render" of the components setup, plus a few helpful comments in each box (so e.g. in the collector box, you would provide the HTTP endpoint; in the ES box, you would provide the link to the _head plugin or whatever)...

**Comment by jbeemster** [comment]
It can it can for sure.  I am happy to start small and build up slowly.  It was more an idea of direction of travel that we could go in... might have got a bit carried away.

For a v1 I agree that just a static render of the components and quick links to the different services is all we need.

**Comment by alexanderdean** [comment]
Cool, scheduling... Let's timebox this to 8 hours - as soon as it exceeds that timebox, please move into a separate branch and push back to the next release.

**Comment by jbeemster** [comment]
Do we want to do this React + TypeScript style to set the groundwork for later updates or super simple setup?

**Comment by alexanderdean** [comment]
Whatever works in the timebox is fine
