### ISSUE TITLE
Add Caddy proxy to add embedded TLS support

### ISSUE THREAD

**Issue by rafaelfelix** [snowplow/snowplow-mini#48]
Hi.

This is more a feature request than an issue itself. My website uses SSL (including homolog and staging environments), and I would like to use Snowplow-Mini as the collector for those internal environments.

Besides setting up SSL termination, is there any plan to add out-of-the-box SSL support for the collector? Something like https://letsencrypt.org/ could be used.

Thanks a lot,

**Comment by alexanderdean** [comment]
Cool idea!

**Comment by yalisassoon** [comment]
This is also really key for users that want to test sending events from iOS, which have to be sent over HTTPS

**Comment by alexanderdean** [comment]
I like the idea of using Let's Encrypt. Note that Snowplow Mini will need to have a domain associated with it for a LE certificate to be used ([ref](https://community.letsencrypt.org/t/certificate-for-public-ip-without-domain-name/6082)).

**Comment by dcow** [comment]
+1 This would make iOS easier and configuration of my emitter easier.

**Comment by alexanderdean** [comment]
What actually has to be done here @jbeemster ? Is it as simple as recommending users setup Snowplow Mini in an ELB?

**Comment by alexanderdean** [comment]
(Given we have no plans to add TLS support into the collector itself.)

**Comment by jbeemster** [comment]
That is the easiest solution yes, beyond adding some way to install Nginx and adding a certificate to the box.  I am happy to just add the ELB step to the documentation.

**Comment by alexanderdean** [comment]
Okay great - I've renamed this ticket, de-scheduled it and added in #69

**Comment by alexanderdean** [comment]
This is scheduled for 0.3.0. This approach should drastically simplify the deployment of HTTPS-compatible Snowplow Mini...

**Comment by alexanderdean** [comment]
Closing this as all the work was done in #12
