### ISSUE TITLE
Update to Packer 0.10.0+ and convert shell scripts to ansible playbooks

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-mini#52]

**Comment by alexanderdean** [comment]
Any feedback on this one @jbeemster ?

**Comment by jbeemster** [comment]
@aldemirenes and I had a catchup about this yesterday on how to cleanup the implementation of this process.

**Comment by alexanderdean** [comment]
Thanks @aldemirenes - note that your commit message does not match the ticket name. Not sure which is correct (or neither yet).

**Comment by alexanderdean** [comment]
Looks like @aldemirenes has done another pass on this - does the last commit have the greenlight from you @jbeemster ?
