### ISSUE TITLE
Creating an API key in the Iglu front-end keeps getting a 401 return code

### ISSUE THREAD

**Issue by idanby1** [snowplow/snowplow-mini#53]
From a customer:

"Right now I am trying to create an API key in the Iglu front-end but unfortunately I keep getting a 401 return code while requesting the resource "/api/auth/keygen" (after introducing the master API key in the top right corner), whereas by using Curl I get a successful result with the command below:

$ curl http://XX.XX.XX.XX:8081/api/auth/keygen -X POST -H "apikey: master-api-key" -d "vendor_prefix=com.xxxxxx"

The only difference I found is that, apparently, the 401 request sent from the front-end (attached image) does not include the "apikey" header, so by adding this header value from the web browser console I am able to make it work. I do not know if you were aware about this particular, that is why I wanted to mail you. Besides this, I will try to go on with the installation by using Curl."

**Comment by chuwy** [comment]
Hey @idanby1! This is a known bug in Iglu Scala Server https://github.com/snowplow/iglu/issues/125

**Comment by oguzhanunlu** [comment]
This is handled in a previous Iglu Server release and not applicable for Mini anymore, closing
