### ISSUE TITLE
Create the Snowplow Mini control plane API

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-mini#56]
Unauthenticated API written in Golang, should be RESTful.

Some ideas for the API over time (not all for this release):

- Restarting individual applications
- Resetting caches (Stream Enrich / Iglu Server)
- Deleting Elasticsearch stored events
- Sending Events with a blocking feedback loop on the event making it into Elasticsearch
  - You send the event to the API instead -> forwards to the collector -> we then wait for the event to reach Elasticsearch (Good or Bad) -> Report back with 200 or 400 and the JSON found in Elasticsearch

Any other thoughts @alexanderdean ?

**Comment by alexanderdean** [comment]
No I think this is a great set of features. We should also have another end-point where you can retrieve a specific event using its event_id...

**Comment by jbeemster** [comment]
Oh yeah that would be nice.  As well as maybe an end to end health check where it pings the collector health endpoint, sends a simple event, checks that it has made it so we can quickly assert that Snowplow Mini is happy.

**Comment by alexanderdean** [comment]
Do we want to ship a UI *inside* Snowplow Mini to interact with the Control Plane, or a snowplowminictl CLI *outside* Snowplow to interact with it?

**Comment by jbeemster** [comment]
I would think we could probably do both?  The UI is probably faster initially.

**Comment by alexanderdean** [comment]
So to save time we can probably skip authentication on the Control Plane - the thinking being that if you can access HTTP(S) on the Snowplow Mini (thanks to IP whitelisting), you can invoke the Control Plane's methods.

**Comment by alexanderdean** [comment]
Note that for 0.3.0, this is just creating the API. Specific API functions supported in 0.3.0 will be only #82

**Comment by alexanderdean** [comment]
Hey @aldemirenes - this issue didn't close with the release. Unassign and close?
