### ISSUE TITLE
Remove legacy iglu_server_upload.sh script

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-mini#58]
We are using a Python insert in the script to parse the returned JSON, this is only compatible with 2.X and will throw errors on newer versions of Python.

Change to: `print statement to 'print(obj["status"])'`

**Comment by alexanderdean** [comment]
This should be superceded by igluctl - @chuwy should have the details...

**Comment by chuwy** [comment]
Hey @jbeemster. Currently I have a full port of `iglu_upload_script` written in Scala (planning to release it on next week with Iglu 5). If you have any new features on your mind - just create corresponding ticket in snowplow/iglu.

**Comment by jbeemster** [comment]
Hey @chuwy! No extra ideas we just needed to make a note of this as the current script is breaking upload for those on Python 3.X.  

How would users go about using the scalafied script with snowplow-mini?

**Comment by chuwy** [comment]
Hm that's a good question. I think we're comparing here plain python script (python interpreter is installed on about 99% of modern computers) and jar (JRE is installed on fewer machines, I guess). 

Do we bundle any more CLI tools along with snowplow-mini?

**Comment by alexanderdean** [comment]
Fixed title

**Comment by yalisassoon** [comment]
I think this is done - we instruct clients to use:

```
$ /path/to/igluctl static push /path/to/schemas/com.mycompany {{ snowplow-mini ip }}:8081 {{ snowplow-mini iglu server key (uuid) }}
```

The full instructions we share with clients is here: https://github.com/snowplow/iglu-example-schema-registry/blob/master/README.md

**Comment by alexanderdean** [comment]
Right - so this is probably just about deleting any legacy scripts from the repo...

**Comment by alexanderdean** [comment]
Improved title, please reword commit
