### ISSUE TITLE
Add button in UI to restart all services

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-mini#59]
We frequently find that at organizations using snowplow-mini for testing / staging, the (often front end) developers doing that testing do not have access to the Snowplow AWS to reboot the snowplow-mini instance. (In any case, rebooting an EC2 instance in an account with a production pipeline is not to be taken lightly.) 

It would be nice if there was an easier way to clear the schema cache, ideally available through the snowplow-mini front end.

**Comment by jbeemster** [comment]
Also noted in this ticket: https://github.com/snowplow/snowplow-mini/issues/56

**Comment by alexanderdean** [comment]
Tweaked title, please reword commit.

Also, in the UI it should make it clear that this button restarts all services. Add a tooltip next to the button which says that this will also clear the cache for schemas.
