### ISSUE TITLE
Develop dashboard in Kibana for visualizing data

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-mini#6]

**Comment by yalisassoon** [comment]
The best way of visualizing the data in Kibana is the Discover interface. This will change when we have categories of errors that we can aggregate over, but whilst each error message is a snowflake (in the sense of being unique) we can't meaningfully aggregate over the bad data.

Suggest for that reason we close this issue.

**Comment by alexanderdean** [comment]
Okay let's close
