### ISSUE TITLE
Cross domain tracking with Snowplow mini

### ISSUE THREAD

**Issue by mariusgold** [snowplow/snowplow-mini#65]
Hey guys,

Just set up a functionnal snowplow mini interface and can collect data from 2 external sites. 
The only issue I have now is to track user between the 2 platforms.

`network_userid ` values are different and `user_id` is just empty while I have the  same `sp_id` in the cookies in debugger tools such as Fiddler or Chrome Console.
Do you know what kind of value I can use to identify a visitor across the 2 platforms?

Thanks

**Comment by alexanderdean** [comment]
Hey @mariusgold ! Our Discourse forums are the best place for support: http://discourse.snowplowanalytics.com/
