### ISSUE TITLE
Add Control Plane API call to put your own custom enrichments in Snowplow Mini

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-mini#66]
This is really useful e.g. to test Javascript enrichments before putting them live on production clients.

Note that it is currently possible to do this manually by sshing into the box, adding the enrichments json, editing an `init.d` file and then rebooting.

**Comment by miike** [comment]
For reference if anybody would like to test enrichments in Snowplow Mini.

1) SSH into the Snowplow mini machine
`ssh -i private-key.pem ubuntu@IP`
2) Create a directory to store enrichments
`mkdir snowplow/configs/enrichments`
3) Copy or create a new file containing the enrichment. The enrichment should follow the format [here](https://github.com/snowplow/snowplow/wiki/Configurable-enrichments). If the enrichment relies on additional schemas these should be uploaded to the Iglu server using the API.
`vim snowplow/configs/enrichments/example.json`
4) Add the --enrichments folder to the init.d file for stream enrich.
`sudo vim /etc/init.d/snowplow_stream_enrich_0.7.0`
5) Add `--enrichments file:/home/ubuntu/snowplow/configs/enrichments` to the end of the string in the cmd= string.
6) Save the file
7) Reboot the machine
`sudo reboot`

When the machine reboots events that now go through the stream enricher should use the enrichments specified in the `enrichments` folder.

**Comment by jbeemster** [comment]
Thanks @miike !  Rather than `sudo reboot` thought we can `sudo service snowplow_stream_enrich_0.7.0 restart` also just to reset that service.

**Comment by miike** [comment]
Yes, that's a much more graceful way of handling it. I've updated my comment above to reflect that.

**Comment by jbeemster** [comment]
I will add these steps to the Wiki until such time as this ticket is cleared!

**Comment by jbeemster** [comment]
Link to wiki: https://github.com/snowplow/snowplow-mini/wiki/Quickstart-guide#custom-enrichments

**Comment by alexanderdean** [comment]
Pushing back...

**Comment by alexanderdean** [comment]
I think you can rename this ticket to become one of the Control Plane API tickets
