### ISSUE TITLE
Bump JavaScript Tracker to 2.8.2

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow-mini#71]
Update the Javascript tracker in Snowplow Mini from 2.6.0 to 2.7.0 (latest)

**Comment by aldemirenes** [comment]
This can be done in version 0.3.0 I think. Is it okay if I make this in version 0.3.0 @alexanderdean?

**Comment by alexanderdean** [comment]
Let's leave for next

**Comment by chuwy** [comment]
Hey @aldemirenes! Just a heads-up - JS Tracker 2.8.1 is the latest version.

**Comment by alexanderdean** [comment]
Improved ticket name, please update commit and changelog
