### ISSUE TITLE
Invisible replacement of EC2 instance on reboot deletes schemas

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-mini#74]
Could we work around by storing schemas in an attached EBS volume?

**Comment by jbeemster** [comment]
So the schemas are stored in the local postgres database which is on an EBS volume.  The trick would be having an autoscaling group automatically reattach to said EBS volume.

By "Invisible replacement" do you mean a termination and replacement event?

**Comment by alexanderdean** [comment]
Speaking to @yalisassoon , we believe that sometimes when you reboot an instance within an ASG, AWS will silently replace that instance with an all-new server. This is consistent with other things I've seen in AWS...

**Comment by jbeemster** [comment]
Ahh yes that could happen.. the only way around that would be to setup Iglu Server as a separate dependency to Snowplow Mini - keep all of the state of the box.

**Comment by jbeemster** [comment]
Hey @alexanderdean - so we have now figured out the reboot & replace phenomena.  Can this ticket be closed in favour of the stateless tickets?

**Comment by alexanderdean** [comment]
Yes, let's close
