### ISSUE TITLE
Bump Elasticsearch & Kibana to version 5.6.10

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-mini#79]

**Comment by jbeemster** [comment]
@alexanderdean this feels like it would be a relatively small amount of work but hugely useful in terms of overall usability / stability of Snowplow Mini.

Thoughts?

**Comment by alexanderdean** [comment]
SGTM!

**Comment by alexanderdean** [comment]
Was this taken out of scope @BenFradet ?

**Comment by BenFradet** [comment]
yes this was discussed in #129 as too resource-hungry, the update lives in the v0.4.0-es-kibana-upgraded, pushing back.

**Comment by mhadam** [comment]
Re: Kibana, there's a bug in the search box[1]. It seems like using chrome w/ this extension[2] is a quick fix in the meantime.


[1] : https://github.com/elastic/kibana/issues/7801

[2] : https://chrome.google.com/webstore/detail/kibana-fixify/malbepndklhdndhmmfkbdchhmnbhnllg?hl=en

**Comment by alexanderdean** [comment]
What is the implication for minimum viable box size?

**Comment by oguzhanunlu** [comment]
This is handled as part of dockerization sp mini, see #23 .
