### ISSUE TITLE
Only storing 7 days of data in elasticsearch?

### ISSUE THREAD

**Issue by brennebeck** [snowplow/snowplow-mini#91]
Hi,

I'm currently testing snowplow-mini in preparation for a production deployment of snowplow. An issue I just encountered is the `good` index seem to only hold 7 days of data? This is around 316k-456k+ docs. Do you know what is causing this? I.e. do does snowplow{-mini} have a setting/tool that clears the ES index except for the recent 7 days? Additionally, where is the rest of the data being stored? I don't see it in pg?

Thanks in advance!

**Comment by alexanderdean** [comment]
Hey @brennebeck - can you ask support questions on our forums please:

http://discourse.snowplowanalytics.com/
