### ISSUE TITLE
Enable third-party cookie set by collector

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-mini#93]
https://github.com/snowplow/snowplow-mini/blob/master/resources/configs/snowplow-stream-collector.hocon#L37-L48

```
Comment out this line to tie cookies to
    # the collector's full domain
domain = ""
```

**Comment by leonmaas** [comment]
Once done we should edit the [quickstart guide](https://github.com/snowplow/snowplow-mini/wiki/Quickstart-guide)

**Comment by alexanderdean** [comment]
-> branch please...
