### ISSUE TITLE
Events not appearing in any index 

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-mini#95]
See:

* http://discourse.snowplowanalytics.com/t/events-sent-to-snowplow-mini-not-appearing-in-any-index/991
* https://snowplow.zendesk.com/agent/tickets/4800 (private)

**Comment by alexanderdean** [comment]
We don't know if this is going to be an easy fix (maybe e.g. a char encoding glitch with Unix pipes), or is just random loss and will only be fixed when we do the NSQ re-write...

**Comment by alexanderdean** [comment]
Pushing back...

**Comment by alexanderdean** [comment]
Do we push back @BenFradet ?

**Comment by oguzhanunlu** [comment]
Closing as we migrated from unix pipes a long time ago
