### ISSUE TITLE
Configure Packerfile.json and ansible playbooks for using ansible playbooks with Packer

### ISSUE THREAD

**Issue by aldemirenes** [snowplow/snowplow-mini#97]

**Comment by alexanderdean** [comment]
Can you write a desciption of the goal into this ticket please Enes?

**Comment by aldemirenes** [comment]
In the Snowplow-Mini v0.2.2, shell scripts are used for provisioning with Packer. But in the Snowplow-Mini v.0.3.0, provisioning will be made with ansible playbooks. Packerfile.json will be updated to use ansible playbooks in the provisioning with Packer. Also, different playbook will be created for provisioning with Packer because there is no need to install packages for compilation of the UI files. UI files are getting ready while vagrant machine is getting up and prepared UI files can be copied directly from vagrant machine to remote machine with Packer provisioning.

**Comment by alexanderdean** [comment]
I think @jbeemster is going to help out with this one.

**Comment by aldemirenes** [comment]
Merged with [this ticket](https://github.com/snowplow/snowplow-mini/issues/52), closing
