### ISSUE TITLE
Remove UI setup from travis build

### ISSUE THREAD

**Issue by aldemirenes** [snowplow/snowplow-mini#98]

**Comment by alexanderdean** [comment]
Can you clarify what this ticket is doing? Can't reconcile the ticket name and the commit contents... Also you haven't added it to a milestone.

**Comment by aldemirenes** [comment]
There was one ansible playbook which setup everything. This includes compiling UI elements and necessary environment for compilation. But this is not necessary for travis build because there is no check for UI elements in the travis. Therefore, new playbook is created for travis build which does not include installation of the UI related packages.

**Comment by aldemirenes** [comment]
@alexanderdean I think comment, which you made in ticket #100, is applicable for this ticket too. Therefore, commit for this ticket is merged with commit for ticket #102

**Comment by alexanderdean** [comment]
Fair!

**Comment by alexanderdean** [comment]
Descheduled
