### ISSUE TITLE
Serve GeoLiteCity.dat file with Caddy server for using in the ip-lookup enrichment

### ISSUE THREAD

**Issue by aldemirenes** [snowplow/snowplow-mini#99]

**Comment by alexanderdean** [comment]
Please add to milestone! Nicely done Enes.

**Comment by alexanderdean** [comment]
You shouldn't need this - this URL works for me:

```
http://s3-eu-west-1.amazonaws.com/snowplow-hosted-assets/third-party/maxmind/GeoLiteCity.dat
```

/cc @jbeemster

**Comment by aldemirenes** [comment]
I was using [this example config](https://github.com/snowplow/snowplow/wiki/IP-lookups-enrichment), url in the example config is inaccessible. But I will change url to what you mentioned in the comment, on the snowplow-mini.

**Comment by alexanderdean** [comment]
Not needed
